# This is a basic workflow to help you get started with Actions

name: Single wf file for all branches

# Controls when the workflow will run
on: 
  push:
  pull_request:
    branches: 
      - master
      - 'releases/**'
      - dev
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Add SHORT_SHA env property with double colon
        run: echo "SHORT_COMMIT_SHA=`echo ${GITHUB_SHA::8}`" >> $GITHUB_ENV
        
      - name: Add SHORT_SHA env property with bash cut
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-12`" >> $GITHUB_ENV   
        
      - name: Set release env
        if: contains(github.ref,'release')
        run: |
          echo "DOCKER_TAG= release" >> $GITHUB_ENV  
          echo "CONTAINER_NAME= releasecontainer" >> $GITHUB_ENV  
          echo "DNS_NAME= nodementorrelease" >> $GITHUB_ENV          
    
      - name: Set master env
        if: contains(github.ref,'master')
        run: |
          echo "DOCKER_TAG= latest" >> $GITHUB_ENV  
          echo "CONTAINER_NAME= prodcontainer" >> $GITHUB_ENV  
          echo "DNS_NAME= nodementorrelease" >> $GITHUB_ENV         
        
      - name: Set dev env
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "CONTAINER_NAME= containerdev" >> $GITHUB_ENV  
          echo "DNS_NAME= nodementordev" >> $GITHUB_ENV  
          echo "DOCKER_TAG= ${{env.SHORT_COMMIT_SHA}}" >> $GITHUB_ENV         
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Workflow on dev branch
          echo $GITHUB_SHA
          echo ${GITHUB_SHA::7}
          echo ${SHORT_SHA}
          echo ${SHORT_COMMIT_SHA}
          echo 'branch variables:'
          echo ${{env.DOCKER_TAG}}
          echo ${{env.CONTAINER_NAME}}
          echo ${{env.DNS_NAME}}
      
      - name: If dev    
        if: github.ref == 'refs/heads/dev'
        run: |
          echo 'dev'
          echo ${{github.ref}}
      
      - name: If master   
        if: github.ref == 'refs/heads/master'
        run: |
          echo 'master'
          echo ${{github.ref}}
