# This is a basic workflow to help you get started with Actions

name: DevCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Add SHORT_SHA env property with double colon
        run: echo "SHORT_COMMIT_SHA=`echo ${GITHUB_SHA::8}`" >> $GITHUB_ENV
        
      - name: Add SHORT_SHA env property with bash cut
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV   
        env:
            DOCKER_TAG: devtag
      #if: github.ref == 'refs/heads/dev'
      
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Workflow on dev branch
          echo $GITHUB_SHA
          echo ${GITHUB_SHA::7}
          echo ${SHORT_SHA}
          echo ${SHORT_COMMIT_SHA}
          echo DOCKER TAG:
          echo ${{DOCKER_TAG}}
      
      - name: If dev    
        if: github.ref == 'refs/heads/dev'
        run: |
          echo 'dev'
          echo ${{github.ref}}
      
      - name: If master   
        if: github.ref == 'refs/heads/master'
        run: |
          echo 'master'
          echo ${{github.ref}}
